# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Required
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Optional but recommended
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation from this directory
sphinx:
  configuration: docs/source/conf.py
